---
title: "Untitled"
author: "Adam Black"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(DatabaseConnector)
library(dplyr, warn.conflicts = FALSE)
library(here)
library(glue)

ParallelLogger::logInfo("asdf")


# Database Connection info
connectionDetails <- createConnectionDetails(dbms = "postgresql",
                                             server = "localhost/synpuf100k",
                                             user = "postgres",
                                             password = "")

cdmDatabaseSchema = "cdm531"
cohortDatabaseSchema = "scratch"
cohortTable = "cohort"



start <- Sys.time()

cohortStagingTable <- paste0(cohortTable, "_stg")

cohortDefinitionSet <- 
  readr::read_csv(here::here("input", "settings", "CohortsToCreate.csv"), show_col_types = FALSE) %>% 
  mutate(cohortName = name,
         sqlPath = here("input", "sql", paste0(name, ".sql")),
         sql = purrr::map_chr(sqlPath, readr::read_file))

cohortTableNames <- CohortGenerator::getCohortTableNames(cohortStagingTable)

CohortGenerator::createCohortTables(
  connectionDetails = connectionDetails,
  cohortDatabaseSchema = cohortDatabaseSchema,
  cohortTableNames = cohortTableNames,
  incremental = TRUE
)




```

